# @name create-user
POST http://localhost:3333/users/create
Content-Type: application/json

{
  "name": "user",
  "email": "user@hotmail.com",
  "login": "user_login",
  "cpf": "06303977758",
  "password": "123456789"
}

###

# @name login-user
POST http://localhost:3333/users/login
Content-Type: application/json

{
  "login": "user@hotmail.com",
  "password": "123456789"
}

###

# @name delete-user
DELETE  http://localhost:3333/users/13/delete

###

# @name update-user
PUT http://localhost:3333/users/13/update
Content-Type: application/json

{
  "name": "novo_nome",
  "password": "nova_senha"
}

###

# @name transaction
PUT http://localhost:3333/users/14/transaction
Content-Type: application/json

{
  "value": 200
}

###

# @name create-student
POST http://localhost:3333/students/create
Content-Type: application/json

{
  "registration": "164008",
  "class": "1-A",
  "spendingLimit": 30,
  "school": "unifesp",
  "userId": 14
}

###

# @name update-student
PUT http://localhost:3333/students/3/update
Content-Type: application/json

{
  "registration": "164008",
  "class": "1-D",
  "spendingLimit": 40,
  "school": "unifesp"
}
