# @name create-user
POST http://localhost:3333/users/create
Content-Type: application/json

{
  "name": "user",
  "email": "user@hotmail.com",
  "login": "user_login",
  "cpf": "06303977758",
  "password": "123456789"
}

###

# @name login-user
POST http://localhost:3333/users/login
Content-Type: application/json

{
  "login": "user_login",
  "password": "123456789"
}

###

# @name delete-user
DELETE  http://localhost:3333/users/11/delete
